"""Generate a living `schema_desc.md` from the PostgreSQL information_schema.

`sync_schema_desc()` is intentionally side-effect-only: it queries the
database directly through the shared connection pool (bypassing
`db_operations.execute_sql` to avoid the DDL hook re-entering itself) and
writes a Markdown snapshot of every base table in the target schema, with
column types, nullability, defaults, and any comments stored in
`pg_description`. This file is meant to be read by the agent before every
SQL write so it does not hallucinate column names.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import psycopg2

import db_operations


SCHEMA_DESC_PATH = Path("schema_desc.md")
DEFAULT_SCHEMA = "public"


_TABLE_COMMENT_SQL = """
SELECT t.table_name,
       obj_description(c.oid, 'pg_class') AS table_comment
FROM information_schema.tables AS t
JOIN pg_class AS c ON c.relname = t.table_name
JOIN pg_namespace AS n ON n.oid = c.relnamespace AND n.nspname = t.table_schema
WHERE t.table_schema = %s
  AND t.table_type = 'BASE TABLE'
ORDER BY t.table_name;
"""

_COLUMN_SQL = """
SELECT col.table_name,
       col.column_name,
       col.ordinal_position,
       col.data_type,
       col.character_maximum_length,
       col.is_nullable,
       col.column_default,
       col_description(c.oid, col.ordinal_position) AS column_comment
FROM information_schema.columns AS col
JOIN pg_class AS c ON c.relname = col.table_name
JOIN pg_namespace AS n ON n.oid = c.relnamespace AND n.nspname = col.table_schema
WHERE col.table_schema = %s
ORDER BY col.table_name, col.ordinal_position;
"""


def _format_type(data_type: str, char_max_length: int | None) -> str:
    if char_max_length and data_type in {"character varying", "character"}:
        return f"{data_type}({char_max_length})"
    return data_type


def _render_markdown(
    schema: str,
    table_comments: dict[str, str | None],
    columns_by_table: dict[str, list[tuple]],
    generated_at: datetime,
) -> str:
    lines: list[str] = []
    lines.append("# Database Schema")
    lines.append("")
    lines.append(
        f"_Auto-generated by `schema_manager.sync_schema_desc()` at "
        f"{generated_at.isoformat(timespec='seconds')}._"
    )
    lines.append("")
    lines.append(f"Schema: `{schema}`")
    lines.append("")

    if not table_comments:
        lines.append("_No base tables found in this schema._")
        lines.append("")
        return "\n".join(lines)

    for table in sorted(table_comments):
        comment = table_comments.get(table)
        lines.append(f"## `{table}`")
        lines.append("")
        if comment:
            lines.append(comment.strip())
            lines.append("")
        else:
            lines.append("_No table comment. Add one with `COMMENT ON TABLE` to "
                         "explain this table's purpose._")
            lines.append("")

        rows = columns_by_table.get(table, [])
        lines.append("| # | Column | Type | Nullable | Default | Comment |")
        lines.append("|---|--------|------|----------|---------|---------|")
        for row in rows:
            (
                _table_name,
                column_name,
                ordinal,
                data_type,
                char_max_length,
                is_nullable,
                column_default,
                column_comment,
            ) = row
            type_str = _format_type(data_type, char_max_length)
            default_str = column_default if column_default is not None else ""
            comment_str = (column_comment or "").replace("|", "\\|").replace("\n", " ")
            lines.append(
                f"| {ordinal} | `{column_name}` | `{type_str}` | "
                f"{is_nullable} | `{default_str}` | {comment_str} |"
            )
        lines.append("")

    return "\n".join(lines)


def sync_schema_desc(
    output_path: Path | str = SCHEMA_DESC_PATH,
    schema: str = DEFAULT_SCHEMA,
) -> str:
    """Refresh the schema description Markdown file. Returns a status string."""
    output_path = Path(output_path)

    pool_ = db_operations._get_pool()
    conn = pool_.getconn()
    try:
        try:
            with conn.cursor() as cur:
                cur.execute(_TABLE_COMMENT_SQL, (schema,))
                table_comments: dict[str, str | None] = {
                    name: comment for name, comment in cur.fetchall()
                }
            with conn.cursor() as cur:
                cur.execute(_COLUMN_SQL, (schema,))
                columns_by_table: dict[str, list[tuple]] = {}
                for row in cur.fetchall():
                    columns_by_table.setdefault(row[0], []).append(row)
            conn.commit()
        except psycopg2.Error as exc:
            conn.rollback()
            return f"error: schema sync query failed: {exc}"
    finally:
        pool_.putconn(conn)

    # Make sure orphan tables (with columns but no entry in table_comments)
    # don't get silently dropped. information_schema.tables is the source
    # of truth for table existence, so add empty entries if needed.
    for table_name in columns_by_table:
        table_comments.setdefault(table_name, None)

    markdown = _render_markdown(
        schema=schema,
        table_comments=table_comments,
        columns_by_table=columns_by_table,
        generated_at=datetime.now(tz=timezone.utc),
    )

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(markdown, encoding="utf-8")
    except OSError as exc:
        return f"error: could not write {output_path}: {exc}"

    return f"ok: wrote {len(table_comments)} table(s) to {output_path}"
